import java.util.*

data class UserList(
        val members: Array<User>
) : PaginatedCursor() {

    /*
    Autogenerated equals and hashcode
     */
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as UserList

        if (!Arrays.equals(members, other.members)) return false

        return true
    }

    override fun hashCode(): Int {
        return Arrays.hashCode(members)
    }
}